<section class="slider-block">
	<div class="owl-carousel owl-theme">
		<div class="item">
			<img src="<?php echo $this->getViewFileUrl('images/static/home-banner-1.jpg'); ?>" alt="Demo">
			<div class="slider-content">
				<div class="slider-content-inner">
					<div class="container">
						<div class="row">
							<h4>dfsdf 2sdaf a2222</h4>
							<h4>dfsdfasdf asfasd</h4>
							<h4>dfsdfasdf asfasd</h4>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="item">
			<img src="<?php echo $this->getViewFileUrl('images/static/home-banner-1.jpg'); ?>" alt="Demo">
			<div class="slider-content">
				<div class="slider-content-inner">
					<div class="container">
						<div class="row">
							<h4>dfsdf 2sdaf a2222</h4>
							<h4>dfsdfasdf asfasd</h4>
							<h4>dfsdfasdf asfasd</h4>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="ngo-help-section section-block">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-6 col-md-offset-3">
				<div class="ngo-section-title">
					<h2>HOW CAN YOU HELP</h2>
					<div class="ngo-title-line">
						<div class="ngo-title-icon">
							<img src="<?php echo $this->getViewFileUrl('images/static/icon.png'); ?>" alt="Demo">
						</div>
					</div>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority robiul suffered alteration in some form, by injected </p>
				</div>
			</div>
		</div>
		<div class="row ">
			<div class="col-md-4 col-sm-4 ngo-col-padd-less">
				<div class="ngo-help-box bg1">
					<i class="fa fa-child" aria-hidden="true"></i>
					<h4>Become A Volunteer</h4>
					<p>There are many variations of passages of Lorem Ipsum available but by injected.</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 ngo-col-padd-less">
				<div class="ngo-help-box bg2 ngo-middle-box">
					<i class="fa fa-usd" aria-hidden="true"></i>
					<h4>Give Donation</h4>
					<p>There are many variations of passages of Lorem Ipsum available but by injected.</p>
					<a class="btn ngo-btn-donate ngo-btn-transparent" href="#" role="button">DONATE NOW</a>					
				</div>
			</div>
			<div class="col-md-4 col-sm-4 ngo-col-padd-less">
				<div class="ngo-help-box bg3">
					<!--<i class="fa fa-life-ring" aria-hidden="true"></i>-->
					<i class="fa fa-heart" aria-hidden="true"></i>
					<h4>Give Support</h4>
					<p>There are many variations of passages of Lorem Ipsum available but by injected.</p>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="ngo-divider-field section-block" >
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-12">
				<div class="ngo-divider-col text-center">
					<h5>Urgent Causes</h5>
					<h2>Helping Children In africa</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmodtin didunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex</p>
					<div class="ngo-double-button">
						
						<button class="btn ngo-btn-donate" type="submit">DONATE NOW</button>
						<button class="btn ngo-btn-join" type="submit">JOIN WITH US</button>
					</div>
				</div>	
			</div>
			<div class="col-md-1 col-sm-12">
				<div class="ngo-divider-col text-center ngo-vertical-text">
					<p>J</p>
					<p>o</p>
					<p>i</p>
					<p>n</p>
					<br>
					<p>u</p>
					<p>s</p>
				</div>
			</div>
			<div class="col-md-5 col-sm-12">
				<div class="ngo-divider-col clearfix">
					<ul class="ngo-ends-date">
						<li>
							
							<a class="ngo-time-sircle">
								<span class="ngo-funfact clearfix">
									<i class="fa fa-facebook"><span>Facebook</span></i>
								</span>
							</a>
						</li>
						
						<li>
							<a class="ngo-time-sircle">
								<span class="ngo-funfact clearfix">
									<i class="fa fa-twitter"><span>Twitter</span></i>
								</span>
							</a>
							
						</li>
						
						<li>
							<a class="ngo-time-sircle">
								<span class="ngo-funfact clearfix">
									<i class="fa fa-instagram"><span>Instagram</span></i>
								</span>
							</a>
							
						</li>
						<li>
							<a class="ngo-time-sircle">
								<span class="ngo-funfact clearfix">
									<i class="fa fa-linkedin"><span>Linkedin</span></i>
								</span>
							</a>
							
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="ngo-campaign-field section-block">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-6 col-md-offset-3">
				<div class="ngo-section-title">
					<h2>latest campaign</h2>
					<div class="ngo-title-line">
						<div class="ngo-title-icon">
							<img src="<?php echo $this->getViewFileUrl('images/static/icon.png'); ?>" alt="Demo">
						</div>
					</div>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority robiul suffered alteration in some form, by injected </p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 col-sm-6">
				<div class="ngo-campaign-col">
					<div class="ngo-campaign-img">
						<img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
						<div class="ngo-urgent"><p><a href="#">urgent</a></p></div>
						<div class="ngo-campaign-img-text">
							<ul class="clearfix">
								<li><p><i class="fa fa-calendar" aria-hidden="true"></i> 25 Days Left</p></li>
								<li class="pull-right"><p><i class="fa fa-map-marker" aria-hidden="true"></i> South Africa</p></li>
							</ul>
						</div>
					</div>
					<div class="ngo-campaign-content">
						<h4>Charity For Education</h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipisi elit, sed do eiusmod tempor</p>
						
						<a class="btn ngo-btn-donate ngo-btn-transparent" href="#" role="button">DONATE NOW</a>
						
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="ngo-campaign-col">
					<div class="ngo-campaign-img">
						<img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
						<div class="ngo-urgent"><p><a href="#">urgent</a></p></div>
						<div class="ngo-campaign-img-text">
							<ul class="clearfix">
								<li><p><i class="fa fa-calendar" aria-hidden="true"></i> 25 Days Left</p></li>
								<li class="pull-right"><p><i class="fa fa-map-marker" aria-hidden="true"></i> South Africa</p></li>
							</ul>
						</div>
					</div>
					<div class="ngo-campaign-content">
						<h4>Africa Children Need More Food</h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipisi elit, sed do eiusmod tempor</p>
						<a class="btn ngo-btn-donate ngo-btn-transparent" href="#" role="button">DONATE NOW</a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="ngo-campaign-col">
					<div class="ngo-campaign-img">
						<img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
						<div class="ngo-urgent"><p><a href="#">urgent</a></p></div>
						<div class="ngo-campaign-img-text">
							<ul class="clearfix">
								<li><p><i class="fa fa-calendar" aria-hidden="true"></i> 25 Days Left</p></li>
								<li class="pull-right"><p><i class="fa fa-map-marker" aria-hidden="true"></i> South Africa</p></li>
							</ul>
						</div>
					</div>
					<div class="ngo-campaign-content">
						<h4>Children For Foods</h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipisi elit, sed do eiusmod tempor</p>
						
						<a class="btn ngo-btn-donate ngo-btn-transparent" href="#" role="button">DONATE NOW</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="ngo-counter-field section-block">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-sm-6 col-xs-6">
				<div class="ngo-counter-col">
					<div class="ngo-funfact">
						<i class="fa fa-users" aria-hidden="true"></i>
						<div class="start-count">10802</div>
						<span>+</span>
						<div class="clearfix"></div>
						<h4>Volunteers</h4>
					</div>
				</div>	
			</div>
			<div class="col-md-3 col-sm-6 col-xs-6">
				<div class="ngo-counter-col">
					<div class="ngo-funfact">
						<i class="fa fa-thumbs-up" aria-hidden="true"></i>
						<div class="start-count">807023</div>
						<span>+</span>
						<div class="clearfix"></div>
						<h4>Casuses</h4>
					</div>
				</div>	
			</div>
			<div class="col-md-3 col-sm-6 col-xs-6">
				<div class="ngo-counter-col">
					<div class="ngo-funfact">
						<i class="fa fa-gift" aria-hidden="true"></i>
						<div class="start-count">10807</div>
						<span>+</span>
						<div class="clearfix"></div>
						<h4>Donators</h4>
					</div>
				</div>	
			</div>
			<div class="col-md-3 col-sm-6 col-xs-6">
				<div class="ngo-counter-col">
					<div class="ngo-funfact">
						<i class="fa fa-heartbeat" aria-hidden="true"></i>
						<div class="start-count">1080</div>
						<span>+</span>
						<div class="clearfix"></div>
						<h4>Saved</h4>
					</div>
				</div>	
			</div>
		</div>
	</div>
</section>
<section class="ngo-volunteers-field section-block">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-6 col-md-offset-3">
				<div class="ngo-section-title">
					<h2>Our Volunteers</h2>
					<div class="ngo-title-line">
						<div class="ngo-title-icon">
							<img src="<?php echo $this->getViewFileUrl('images/static/icon.png'); ?>" alt="Demo">
						</div>
					</div>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority robiul suffered alteration in some form, by injected </p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 col-sm-6">
				<div class="ngo-volunteer-col">
					<img src="<?php echo $this->getViewFileUrl('images/static/volunteer.jpg'); ?>" alt="Demo">
					<div class="ngo-volunteer-name">
						<h4>Robiul Siddikee</h4>
						<p>Volunteers</p>
					</div>
					<div class="ngo-volunteer-name-two">
						<h4><a href="profile.html">Robiul Siddikee</a></h4>
						<p>Volunteers</p>
						<div class="ngo-volunteer-social">
							<a href="#"><i class="fa fa-facebook"><span>Facebook</span></i></a>
							
							<a href="#"><i class="fa fa-instagram"><span>Instagram</span></i></a>
							<a href="#"><i class="fa fa-twitter"><span>Twitter</span></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="ngo-volunteer-col">
					<img src="<?php echo $this->getViewFileUrl('images/static/volunteer.jpg'); ?>" alt="Demo">
					<div class="ngo-volunteer-name">
						<h4>Lara Martins</h4>
						<p>Volunteers</p>
					</div>
					<div class="ngo-volunteer-name-two">
						<h4><a href="profile.html">Lara Martins</a></h4>
						<p>Volunteers</p>
						<div class="ngo-volunteer-social">
							<a href="#"><i class="fa fa-facebook"><span>Facebook</span></i></a>
							
							<a href="#"><i class="fa fa-instagram"><span>Instagram</span></i></a>
							<a href="#"><i class="fa fa-twitter"><span>Twitter</span></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="ngo-volunteer-col">
					<img src="<?php echo $this->getViewFileUrl('images/static/volunteer.jpg'); ?>" alt="Demo">
					<div class="ngo-volunteer-name">
						<h4>Leonor Costa</h4>
						<p>Volunteers</p>
					</div>
					<div class="ngo-volunteer-name-two">
						<h4><a href="profile.html">Leonor Costa</a></h4>
						<p>Volunteers</p>
						<div class="ngo-volunteer-social">
							<a href="#"><i class="fa fa-facebook"><span>Facebook</span></i></a>
							
							<a href="#"><i class="fa fa-instagram"><span>Instagram</span></i></a>
							<a href="#"><i class="fa fa-twitter"><span>Twitter</span></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="ngo-volunteer-col">
					<img src="<?php echo $this->getViewFileUrl('images/static/volunteer.jpg'); ?>" alt="Demo">
					<div class="ngo-volunteer-name">
						<h4>Maria Jesus</h4>
						<p>Volunteers</p>
					</div>
					<div class="ngo-volunteer-name-two">
						<h4><a href="profile.html">Maria Jesus</a></h4>
						<p>Volunteers</p>
						<div class="ngo-volunteer-social">
							<a href="#"><i class="fa fa-facebook"><span>Facebook</span></i></a>
							
							<a href="#"><i class="fa fa-instagram"><span>Instagram</span></i></a>
							<a href="#"><i class="fa fa-twitter"><span>Twitter</span></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="ngo-gallery-field section-block">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-6 col-md-offset-3">
				<div class="ngo-section-title">
					<h2>our gallery</h2>
					<div class="ngo-title-line">
						<div class="ngo-title-icon">
							<img src="<?php echo $this->getViewFileUrl('images/static/icon.png'); ?>" alt="Demo">
						</div>
					</div>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority robiul suffered alteration in some form, by injected </p>
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-3 col-sm-6 ngo-col-padd-less">
				<div class="ngo-img-hover">
                    <img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
                    <div class="ngo-layer">
	                    <a class="lightbox-image" href="#" >
	                    	<i class="fa fa-arrows-alt" aria-hidden="true"></i>
	                    </a>
                    </div>
                </div>	
			</div>
			<div class="col-md-3 col-sm-6 ngo-col-padd-less">
				<div class="ngo-img-hover">
                    <img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
                    <div class="ngo-layer">
	                    <a class="lightbox-image">
	                    	<i class="fa fa-arrows-alt" aria-hidden="true"></i>
	                    </a>
                    </div>
                </div>	
			</div>
			<div class="col-md-3 col-sm-6 ngo-col-padd-less">
				<div class="ngo-img-hover">
                    <img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
                    <div class="ngo-layer">
	                    <a class="lightbox-image" href="#" >
	                    	<i class="fa fa-arrows-alt" aria-hidden="true"></i>
	                    </a>
                    </div>
                </div>	
			</div>
			<div class="col-md-3 col-sm-6 ngo-col-padd-less">
				<div class="ngo-img-hover">
                    <img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
                    <div class="ngo-layer">
	                    <a class="lightbox-image" href="#" >
	                    	<i class="fa fa-arrows-alt" aria-hidden="true"></i>
	                    </a>
                    </div>
                </div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 col-sm-6 ngo-col-padd-less">
				<div class="ngo-img-hover">
                    <img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
                    <div class="ngo-layer">
	                    <a class="lightbox-image" href="#" >
	                    	<i class="fa fa-arrows-alt" aria-hidden="true"></i>
	                    </a>
                    </div>
                </div>	
			</div>
			<div class="col-md-3 col-sm-6 ngo-col-padd-less">
				<div class="ngo-img-hover">
                    <img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
                    <div class="ngo-layer">
	                    <a class="lightbox-image" href="#" >
	                    	<i class="fa fa-arrows-alt" aria-hidden="true"></i>
	                    </a>
                    </div>
                </div>	
			</div>
			<div class="col-md-3 col-sm-6 ngo-col-padd-less">
				<div class="ngo-img-hover">
                    <img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
                    <div class="ngo-layer">
	                    <a class="lightbox-image" href="#" >
	                    	<i class="fa fa-arrows-alt" aria-hidden="true"></i>
	                    </a>
                    </div>
                </div>	
			</div>
			<div class="col-md-3 col-sm-6 ngo-col-padd-less">
				<div class="ngo-img-hover">
                    <img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
                    <div class="ngo-layer">
	                    <a class="lightbox-image" href="#">
	                    	<i class="fa fa-arrows-alt" aria-hidden="true"></i>
	                    </a>
                    </div>
                </div>	
			</div>
		</div>		
	</div>
</section>
<section class="ngo-blog-field section-block">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-6 col-md-offset-3">
				<div class="ngo-section-title">
					<h2>latest blog</h2>
					<div class="ngo-title-line">
						<div class="ngo-title-icon">
							<img src="<?php echo $this->getViewFileUrl('images/static/icon.png'); ?>" alt="Demo">
						</div>
					</div>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority robiul suffered alteration in some form, by injected </p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 col-sm-6">
				<div class="ngo-campaign-col ngo-blog-col">
					<div class="ngo-campaign-img">
						<img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
						<div class="ngo-campaign-img-text">
							<ul class="clearfix">
								<li><p><i class="fa fa-calendar" aria-hidden="true"></i> <a href="#">14 Sep 2017</a></p></li>
								<li><p><i class="fa fa-eye" aria-hidden="true"></i> <a href="#">65</a></p></li>
								<li><p><i class="fa fa-comment" aria-hidden="true"></i> <a href="#">40</a></p></li>
							</ul>
						</div>
					</div>
					<div class="ngo-campaign-content">
						<h4>Africa Children Need More Food</h4>
						<p>There are many variations of passages of Lorem amr redm Ipsum available, but the majority</p>
						<a class="btn ngo-btn-donate ngo-btn-transparent" href="#" role="button">DONATE NOW</a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="ngo-campaign-col ngo-blog-col">
					<div class="ngo-campaign-img">
						<img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
						<div class="ngo-campaign-img-text">
							<ul class="clearfix">
								<li><p><i class="fa fa-calendar" aria-hidden="true"></i> <a href="#">14 Sep 2017</a></p></li>
								<li><p><i class="fa fa-eye" aria-hidden="true"></i> <a href="#">65</a></p></li>
								<li><p><i class="fa fa-comment" aria-hidden="true"></i> <a href="#">40</a></p></li>
							</ul>
						</div>
					</div>
					<div class="ngo-campaign-content">
						<h4>Africa Children Need More Food</h4>
						<p>There are many variations of passages of Lorem amr redm Ipsum available, but the majority</p>
						<a class="btn ngo-btn-donate ngo-btn-transparent" href="#" role="button">DONATE NOW</a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="ngo-campaign-col ngo-blog-col">
					<div class="ngo-campaign-img">
						<img src="<?php echo $this->getViewFileUrl('images/static/campaign.jpg'); ?>" alt="Demo">
						<div class="ngo-campaign-img-text">
							<ul class="clearfix">
								<li><p><i class="fa fa-calendar" aria-hidden="true"></i> <a href="#">14 Sep 2017</a></p></li>
								<li><p><i class="fa fa-eye" aria-hidden="true"></i> <a href="#">65</a></p></li>
								<li><p><i class="fa fa-comment" aria-hidden="true"></i> <a href="#">40</a></p></li>
							</ul>
						</div>
					</div>
					<div class="ngo-campaign-content">
						<h4>Africa Children Need More Food</h4>
						<p>There are many variations of passages of Lorem amr redm Ipsum available, but the majority</p>
						<a class="btn ngo-btn-donate ngo-btn-transparent" href="#" role="button">DONATE NOW</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>







<script type="text/javascript">
    require(['jquery','owlslider'], function ($) {		
        jQuery('.owl-carousel').owlCarousel({
			loop:true,
			margin:0,
			nav:true,
			responsive:{
				0:{
					items:1
				},
				600:{
					items:1
				},
				1000:{
					items:1
				}
			}
		});
    });
</script>